language: c

services:
    - memcached

before_install:
    - sudo apt-get install libmemcached-dev

env:
    - LUA_VERSION=5.1.5
    - LUA_IMPL=luajit LUA_VERSION=2.0.4
    - LUA_IMPL=luajit LUA_VERSION=2.1.0-beta1

install:
    - make env PLATFORM=linux LUA_IMPL=$LUA_IMPL LUA_VERSION=$LUA_VERSION

script:
    - make lib LIBMEMCACHED_DIR=/usr
    - make test
    - make qa
